name: C++ CI

on:
  pull_request

jobs:
  test:
    name: Tests in ${{ matrix.build_type }} with ${{ matrix.compiler }} 
    runs-on: ubuntu-20.04
    container: ubuntu:21.10
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      matrix:
        build_type: [Release, Debug, RelWithDebInfo]
        compiler: [g++, clang++]

    steps:
    - name: dependencies
      run: |
        apt-get update
        apt-get install -y git build-essential binutils gcc clang cmake valgrind libc++-dev libc++abi-dev libunwind-13-dev
      
    - uses: actions/checkout@v2

    - name: Build main
      run: CXX=${{ matrix.compiler }} ci-extra/build.sh ${{ matrix.build_type }}

    - name: Test main
      run: ci-extra/test.sh ${{ matrix.build_type }}

    - if: ${{ matrix.build_type == 'RelWithDebInfo' }}
      name: Test main with valgrind
      run: ci-extra/test-valgrind.sh
